 - menu_name: "Quick Links"

 - name: "Homepage"
   url: "/"
   title: "Homepage"

 - name: "Library"
   url: "/library"
   title: "Library"
   
 - name: "About"
   url: "/info"
   title: "About"

 - name: "YouTube"
   url: https://www.youtube.com/@Retr0680
   title: "Check out my Videos"